;;; tech49-theme.el --- an Emacs 24 theme based on Tech49 (tmTheme)
;;
;;; Author: Auto Converted to Emacs 24 by tmtheme-to-deftheme (tm2deftheme)
;;; Version: 1403919004
;;; Original author: 
;;; Url: https://github.com/emacsfodder/tmtheme-to-deftheme
;;; Package-Requires: ((emacs "24.0"))
;;
;;; Commentary:
;;  This theme was automatically generated by tmtheme-to-deftheme (tm2deftheme),
;;  from Tech49 (tmTheme) by 
;;
;;; Code:

(deftheme tech49
  "tech49-theme - Created by tmtheme-to-deftheme - 2014-06-28 09:30:04 +0800")

(custom-theme-set-variables
 'tech49
)

(custom-theme-set-faces
 'tech49
 ;; basic theming.

 '(default ((t (:foreground "#accecb" :background "#000000"))))
 '(region  ((t (:background "#3e4e55BB"))))
 '(cursor  ((t (:background "#a1e4f2"))))

 ;; Temporary defaults
 '(linum                               ((t (:foreground "#000000"  :background "#000000" ))))
 '(fringe                              ((t (                       :background "#000000" ))))

 '(minibuffer-prompt                   ((t (:foreground "#1278A8"  :background nil       :weight bold                                  ))))
 '(escape-glyph                        ((t (:foreground "orange"   :background nil                                                     ))))
 '(highlight                           ((t (:foreground "orange"   :background nil                                                     ))))
 '(shadow                              ((t (:foreground "#777777"  :background nil                                                     ))))

 '(trailing-whitespace                 ((t (:foreground "#FFFFFF"  :background "#C74000"                                               ))))
 '(link                                ((t (:foreground "#00b7f0"  :background nil       :underline t                                  ))))
 '(link-visited                        ((t (:foreground "#4488cc"                       :underline t :inherit (link)                  ))))
 '(button                              ((t (:foreground "#FFFFFF"  :background "#444444" :underline t :inherit (link)                  ))))
 '(next-error                          ((t (                                             :inherit (region)                             ))))
 '(query-replace                       ((t (                                             :inherit (isearch)                            ))))
 '(header-line                         ((t (:foreground "#EEEEEE"  :background "#444444" :box nil :inherit (mode-line)                 ))))

 '(mode-line-highlight                 ((t (                                             :box nil                                      ))))
 '(mode-line-emphasis                  ((t (                                             :weight bold                                  ))))
 '(mode-line-buffer-id                 ((t (                                             :box nil :weight bold                         ))))
 '(mode-line-inactive                  ((t (:foreground "#7cb2ad"  :background "#000000" :box nil :weight light :inherit (mode-line)   ))))
 '(mode-line                           ((t (:foreground "#accecb"  :background "#000000" :box nil ))))

 '(isearch                             ((t (:foreground "#99ccee"  :background "#444444"                                               ))))
 '(isearch-fail                        ((t (                       :background "#ffaaaa"                                               ))))
 '(lazy-highlight                      ((t (                       :background "#77bbdd"                                               ))))
 '(match                               ((t (                       :background "#3388cc"                                               ))))

 '(tooltip                             ((t (:foreground "black"    :background "LightYellow" :inherit (variable-pitch)                 ))))

 '(js3-function-param-face             ((t (:foreground "#BFC3A9"                                                                      ))))
 '(js3-external-variable-face          ((t (:foreground "#F0B090"  :bold t                                                             ))))

 '(secondary-selection                 ((t (                       :background "#342858"                                               ))))
 '(cua-rectangle                       ((t (:foreground "#E0E4CC"  :background "#342858" ))))

 ;; Magit hightlight
 '(magit-item-highlight                ((t (:foreground "white" :background "#1278A8" :inherit nil ))))

 ;; flyspell-mode
 '(flyspell-incorrect                  ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flyspell-duplicate                  ((t (:underline "#009945" :background nil :inherit nil ))))

 ;; flymake-mode
 '(flymake-errline                     ((t (:underline "#AA0000" :background nil :inherit nil ))))
 '(flymake-warnline                    ((t (:underline "#009945" :background nil :inherit nil ))))

 ;;git-gutter
 '(git-gutter:added                    ((t (:foreground "#609f60" :bold t))))
 '(git-gutter:modified                 ((t (:foreground "#3388cc" :bold t))))
 '(git-gutter:deleted                  ((t (:foreground "#cc3333" :bold t))))

 '(diff-added                          ((t (:background "#305030"))))
 '(diff-removed                        ((t (:background "#903010"))))
 '(diff-file-header                    ((t (:background "#362145"))))
 '(diff-context                        ((t (:foreground "#E0E4CC"))))
 '(diff-changed                        ((t (:foreground "#3388cc"))))
 '(diff-hunk-header                    ((t (:background "#242130"))))


 '(font-lock-comment-face ((t (:foreground "#3f5459" ))))
 '(font-lock-variable-name-face ((t (:foreground "#fefedb" ))))
 '(font-lock-builtin-face ((t (:foreground "#ff815c" ))))
 '(font-lock-type-face ((t (:foreground "#d9fefd" ))))
 '(font-lock-string-face ((t (:foreground "#9ea485" ))))
 '(font-lock-function-name-face ((t (:foreground "#78cfde" ))))
 '(font-lock-keyword-face ((t (:foreground "#d1dbaf" ))))
 '(font-lock-warning-face ((t (:foreground "#8a291b" :background "#ff815a"))))
 '(diff-removed ((t (:foreground "#ff815a" ))))
 '(diff-added ((t (:foreground "#c4fefd" ))))
 '(diff-changed ((t (:foreground "#fcffc7" ))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#3f5459" ))))

;; Rainbow delimiters
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#6f745d"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#7a7f67"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#858b70"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#8f957b"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#999e87"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#a3a792"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#adb19e"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#b7baa9"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#c0c3b5"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FF0000"))))
) ;; End face definitions

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'tech49)

;; Local Variables:
;; eval: (when (fboundp 'rainbow-mode) (rainbow-mode +1))
;; End:

;;; tech49-theme.el ends here
